### ISSUE TITLE
Significance of RTandT2R function?

### ISSUE THREAD

**Issue by kaitlyngaynor** [skreling/Hopland_Fire_Deer#1]
https://github.com/skreling/Hopland_Fire_Deer/blob/8512645286b7446c27b55c941831910a7fc31d03/Publication_Rcode/01_Movement_Metrics.Rmd#L31

I pulled this function out to the top of the script (no need to copy + paste four times) and am just wondering what the function does? Hoping to annotate it here.

**Comment by skreling** [comment]
Added information from where I got function from
