### ISSUE TITLE
Outlier for Q5

### ISSUE THREAD

**Issue by kaitlyngaynor** [skreling/Hopland_Fire_Deer#2]
https://github.com/skreling/Hopland_Fire_Deer/blob/8512645286b7446c27b55c941831910a7fc31d03/Publication_Rcode/01_Movement_Metrics.Rmd#L66

I ran through the code just to make sure it was all working and looked good, and when plotting the ltraj object for the pre-fire doe, there appears to be one extreme outlier point for Q5. Have you noticed this before? I know this is a hassle at this point.... but it seems like it should probably be removed?

**Comment by skreling** [comment]
Removed point from doe J5 (I assume you meant the far one on J5, not Q5) and it changed nothing in subsequent analyses. Ran all the way through t-tests and nothing changed, but data frame is updated without that point now.

**Comment by kaitlyngaynor** [comment]
You're right; it was J5. I just pulled the repo, though (which includes the updated csv), and it's still showing up when I plot the ltraj objects? Is it fixed on your end?

**Comment by kaitlyngaynor** [comment]
I sorted it out. I think it was still present in one of the files but not the other. I am now streamlining code so that all scripts use the combined buck & doe files rather than the separate ones (and they just get split in the scripts that require separate analysis for buck vs. doe)
