### ISSUE TITLE
Correct displacement t-test in manuscript

### ISSUE THREAD

**Issue by kaitlyngaynor** [skreling/Hopland_Fire_Deer#4]
When I was reviewing the t-test code, I noticed a discrepancy when you subset the displacement script:
`nonfire <- table[c(2,7:8,13, 16),]`
`firedeer <- table[-c(2,7:8,14, 16),]`

13 was included in the non-fire, but 14 was excluded from the fire. It should have been 13 for both. I went ahead and updated this (and used dplyr::filter to select individual deer rather than hard-code the lines removed by number, just to be super sure I was including the right deer) and re-ran the t-test. It didn't change results all that much but does need updating in the manuscript.

See updated here (new t and p-values at the bottom):
https://github.com/skreling/Hopland_Fire_Deer/blob/eee8e1ba3b43096daf063f6caef74307146e1bf9/Publication_Rcode/Collars7_t_tests.Rmd#L21-L41

**Comment by skreling** [comment]
Correct and updated the manuscript.
