### ISSUE TITLE
Including K4 in post-fire doe analysis?

### ISSUE THREAD

**Issue by kaitlyngaynor** [skreling/Hopland_Fire_Deer#5]
After noticing the displacement filtering issue (see #4) I had a closer look at the filtering of does in vs. out of fire perimeter for the other movement metrics. 

The does in the fire perimeter seem to be identified correctly. 

However, when filtering does outside of the fire perimeter (doeOut) you take columns 1, 4, 5, and 10, but this excludes doe K4 (row 18) from the t-test analysis. 

I was going to go through and re-run (see new code that I wrote filtering by ID rather than row number) but wanted to check in first to see if there was any particular reason to exclude K4 from these, or if it was just an oversight

https://github.com/skreling/Hopland_Fire_Deer/blob/57e2c28cd2cc8836f9c0596f10126d2983bca938/Publication_Rcode/Collars7_t_tests.Rmd#L53-L64

**Comment by skreling** [comment]
No this was just a mistake. IDK why i did this with indexing, but I had to redo all the numbers when we combined the dataframes and i likely just left K4 out on accident.

**Comment by kaitlyngaynor** [comment]
Ok great, the t-tests all seem to be the same as in supplementary table 4.

One small change to make, just a rounding thing - in Supplementary Table 4, Pre-fire mean for TAC is 0.508 (not 0.509)
